package lexico;

public enum EnumTokens {
	ID,PR_INTEIRO,PR_FLUTUANTE,PR_E,PR_OU,PR_ENTRADA,PR_IMPRIMIR,PR_IMPRIMIRNL,PR_SE,PR_POREM,
	PR_ENQUANTO,PR_REPITA,PR_INICIO,PR_FIM,PR_FUNCAO,PR_DEVOLVE,PR_CARACTER,
	PR_BOOLEANO,PR_CONJUNTODEPALAVRAS,PR_VERDADE,PR_MENTIRA,PR_NADA,
	PR_VAZIO,PR_PRINCIPAL,OP_ATR,OP_REL,OP_ADI,OP_SUB,OP_MULT,OP_DIV,
	OP_RES,OP_MAIOR,OP_MENOR,OP_MAIORIG,OP_MENORIG,OP_E,OP_OU,OP_NEG,
	OP_NEGUN,OP_RELIGUAL,OP_RELDIFER,DELIM,AB_PAR,FC_PAR,AB_COL,FC_COL,TERMINAL,
	Var,CTE_INT,CTE_FLT,CTE_CDP,CTE_CHR,Fim;

	
}
